~/python3 preprocess_dataset.py --dataset_filename=../datasets/snli_1.0/snli_1.0_train_filtered.tsv --preprocessed_dataset_filename=../datasets/snli_1.0/snli_1.0_train_filtered.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/snli_1.0/snli_1.0_test_filtered.tsv --preprocessed_dataset_filename=../datasets/snli_1.0/snli_1.0_test_filtered.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/snli_1.0/snli_1.0_dev_filtered.tsv --preprocessed_dataset_filename=../datasets/snli_1.0/snli_1.0_dev_filtered.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/SICK/SICK_train.tsv --preprocessed_dataset_filename=../datasets/SICK/SICK/SICK_train.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/SICK/SICK_test.tsv --preprocessed_dataset_filename=../datasets/SICK/SICK/SICK_test.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/SICK/SICK_dev.tsv --preprocessed_dataset_filename=../datasets/SICK/SICK/SICK_dev.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/SICK2/SICK2_train.tsv --preprocessed_dataset_filename=../datasets/SICK/SICK2/SICK2_train.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/SICK2/SICK2_test.tsv --preprocessed_dataset_filename=../datasets/SICK/SICK2/SICK2_test.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/SICK2/SICK2_dev.tsv --preprocessed_dataset_filename=../datasets/SICK/SICK2/SICK2_dev.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/VSICK2/VSICK2_train.tsv --preprocessed_dataset_filename=../datasets/SICK/VSICK2/VSICK2_train.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/VSICK2/VSICK2_test.tsv --preprocessed_dataset_filename=../datasets/SICK/VSICK2/VSICK2_test.tokens
~/python3 preprocess_dataset.py --dataset_filename=../datasets/SICK/VSICK2/VSICK2_dev.tsv --preprocessed_dataset_filename=../datasets/SICK/VSICK2/VSICK2_dev.tokens
